[package]
name = "cargo-featurex"
version = "0.1.3"
edition = "2021"
description = "cargo plugin to run tasks against feature powersets"
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/cargo-featurex"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.12.3", features = ["min_const_generics"] }
cargo_metadata = "0.15.2"
clap = { version = "4.1.1", features = ["derive"] }
error-stack = "0.2.4"
itertools = "0.10.5"
lasso = { version = "0.6.0", features = ["ahasher"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
termcolor = "1.2.0"
thiserror = "1.0.38"
