[package]
name = "cargo-featurex"
version = "0.1.12"
edition = "2021"
description = "cargo plugin to run tasks against feature powersets"
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/cargo-featurex"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitarr = "0.2.0"
cargo_metadata = "0.15.4"
clap = { version = "4.3.2", features = ["derive"] }
error-stack = "0.3.1"
itertools = "0.10.5"
lasso = { version = "0.7.2", features = ["ahasher"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.96" }
termcolor = "1.2.0"
thiserror = "1.0.40"
