[package]
name = "cargo-featurex"
version = "0.1.0"
edition = "2021"
description = "cargo plugin to run tasks against feature powersets"
license = "MIT"
authors = ["Aleksander Heintz <alxandr@alxandr.me>"]
repository = "https://github.com/YoloDev/cargo-featurex"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
cargo_metadata = "0.15.2"
clap = { version = "4.0.29", features = ["derive"] }
error-stack = "0.2.4"
itertools = "0.10.5"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
termcolor = "1.1.3"
thiserror = "1.0.37"
