name: release-please

on:
  push:
    branches: [main]

jobs:
  release_please:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write

    steps:
      - uses: GoogleCloudPlatform/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

      - run: |
          echo "paths_released: ${{ steps.release.outputs.paths_released }}"
          echo "release_created: ${{ steps.release.outputs.paths_released != '[]' }}"

      # - if: ${{ steps.release.outputs.release_created }}
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0

      # - if: ${{ steps.release.outputs.release_created }}
      #   uses: ./.github/workflows/upload-binaries.yml
      #   with:
      #     release: ${{ steps.release.outputs.tag_name }}
    outputs:
      release_created: ${{ steps.release.outputs.paths_released != '[]' }}

  release:
    name: Release to crates.io
    runs-on: ubuntu-latest
    if: needs.release_please.outputs.release_created == 'true'
    needs: release_please

    concurrency:
      group: release

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global fetch.parallel 32
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Install cargo plugins
        run: cargo install cargo-workspaces
      - name: Publish
        run: cargo workspaces publish --from-git --yes --token "${{ secrets.CRATES_IO_TOKEN }}"
